version: '3'

services:
  bolt:
    build: .
    image: bolt
    ports:
      - 8000:80
    volumes:
      - ./bolt/config:/var/www/html/app/config
      - ./bolt/database:/var/www/html/app/database
      - ./bolt/files:/var/www/html/public/files
      - ./bolt/theme:/var/www/html/public/theme
